/*
    alter table product 
        drop constraint FKED8DCCEF13004739;

    alter table product_tag 
        drop constraint FKA71CAC4A7C826CBB;

    alter table product_tag 
        drop constraint FKA71CAC4A712EC15B;
*/
    drop table producer if exists;

    drop table product if exists;

    drop table product_details if exists;

    drop table product_tag if exists;

    drop table tag if exists;

    create table producer (
        producer_id bigint generated by default as identity,
        address varchar(255),
        description varchar(255),
        email varchar(255),
        name varchar(255),
        phone varchar(255),
        primary key (producer_id)
    );

    create table product (
        product_id bigint generated by default as identity,
        name varchar(255),
        description varchar(255),
        price numeric,
        quantity integer,
        producer_id bigint,
        primary key (product_id)
    );

    create table product_details (
        product_details_id bigint generated by default as identity,
        primary key (product_details_id)
    );

    create table product_tag (
        tag_id bigint not null,
        product_id bigint not null,
        primary key (tag_id, product_id)
    );

    create table tag (
        tag_id bigint generated by default as identity,
        value varchar(255),
        primary key (tag_id)
    );

    
    alter table product 
        add constraint FKED8DCCEF13004739 
        foreign key (producer_id) 
        references producer;
	
    
    alter table product_tag 
        add constraint FKA71CAC4A7C826CBB 
        foreign key (product_id) 
        references product;

    alter table product_tag 
        add constraint FKA71CAC4A712EC15B 
        foreign key (tag_id) 
        references tag;
